---
title: Test
timezone: UTC
collections:
  gallery:
    title: Gallery
    output: true
    Items:
    - title: buja
      image: "/uploads/Screen%20Shot%202017-02-03%20at%2009.57.37.png"
    - 
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
